version: "3"

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: interlogica-bakery
    ports:
      - 27017:27017
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - db

  client:
    build:
      context: "./client"
      dockerfile: "Dockerfile.dev"
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./client/src:/app/src
    environment:
      REACT_APP_API_URL: api

  nginx:
    restart: always
    depends_on:
      - api
      - db
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
